### ISSUE TITLE
Error when running jammit 0.6.5 (ruby 1.9.3 + rails 3.2.8 + windows 7 64-bit)

### ISSUE THREAD

**Issue by ngrenier** [documentcloud/jammit#240]
Hi,

I try to use Jammit to build the DocumentViewer from DocumentCloud.

The first error I got when running "jammit" is:
D:/dev/apps/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- win32/open3 (LoadError)

After some research I've installed the gem win32-open3-19, which solved the first error but gives me this second error:
D:/dev/apps/Ruby193/lib/ruby/1.9.1/open3.rb:202:in `spawn': Invalid argument - java -jar D:/dev/apps/Ruby193/lib/ruby/gems/1.9.1/gems/yui-compressor-0.9.6/lib/yui/../yuicompressor-2.4.4.jar --type css --charset utf-8 (Errno::EINVAL)

Any idea about this issue and how to solve it?

Thanks!
Nicolas

**Comment by reefdog** [comment]
Closing this since so many of the components are out of date. If there are still issues with your current stack, feel free to open a new issue!
