### ISSUE TITLE
Segmentation fault when calling rake jammit:package

### ISSUE THREAD

**Issue by DiegoSalazar** [documentcloud/jammit#244]
/data/1SaleADay/shared/bundled_gems/ruby/1.8/gems/jammit-0.6.3/lib/jammit/compressor.rb:249: [BUG] Segmentation fault
ruby 1.8.7 (2011-12-28 patchlevel 357) [x86_64-linux]

sh: line 1:  6031 Aborted                 bundle exec rake jammit:package

(I'm at work so can't be more detailed initially. If someone is interested in this I'll provide more details, or if there's a solution let me know!)

**Comment by reefdog** [comment]
@DiegoSalazar Still having trouble packaging with your latest stack?

**Comment by DiegoSalazar** [comment]
@reefdog well with rails having that built in now I'd have to say no lol
