### ISSUE TITLE
Adding path changes all JST paths

### ISSUE THREAD

**Issue by crystalneth** [documentcloud/jammit#253]
If my assets.yml looks like this:

  project_templates:
    - app/templates/projects/*.jst.haml
    - app/templates/projects/index/*.jst.haml
    - app/templates/projects/show/*.jst.haml

Then then a template in projects/show is compiled into JST['show/foo'].

If I then add another path, like:

  project_templates:
    - app/templates/projects/*.jst.haml
    - app/templates/projects/index/*.jst.haml
    - app/templates/projects/show/*.jst.haml
    - app/templates/documents/shared/*.jst.haml

then the template in projects/show is compiled into JST['projects/show/foo'].

Is this behavior documented or avoidable? This makes going from a single path to multiple paths require modifying and testing a significant existing code, which is quite annoying.

It also seems like generally inconsistent and confusing behavior that discourages sharing code.

**Comment by reefdog** [comment]
Dup of #192.
