### ISSUE TITLE
new tag/release needed to apply patch for Rails 4!

### ISSUE THREAD

**Issue by shaioz** [documentcloud/jammit#256]
Current version (0.6.6) doesn't work, and Heroku actively rejects projects with the latest gem of jammit!

I've temporarily forked and released a version for my uses. (https://github.com/shaioz/jammit)
The problem was fixed 7 months ago here: https://github.com/documentcloud/jammit/commit/461ec6f720b5f767ab0b362ab7dd2836ade4679d but until you release a new version, Bundler will continue to check out 0.6.6 which if broken for RoR 4.

Please release a new version so the gem will be usable again.

Thanks in advance, 
Shai.

**Comment by reefdog** [comment]
Shortly ended up being a bit longer than anticipated, but for those pegged to the `rails4` branch, you can now return to RubyGems proper. Our 0.7.0 has the Rails 4 fixes and a few other things.
