### ISSUE TITLE
Jammit + browser caching + CDNs

### ISSUE THREAD

**Issue by agibralter** [documentcloud/jammit#45]
I was just wondering... would it make sense to build some sort of system into Jammit to allow the browser caching of JS and CSS assets? What I imagine is something like this:

When the `jammit` command gets run, it calculates a MD5 checksum of each package and creates a file, assets.lock.yml in config/. That file could look something like:

```
package1: 50bda6102c8dd57a5ead84e99d493776
package2: 1dd5a5eabda693707672c8d84e99d450
```

It also symlinks (or copies) each package to have its MD5 checksum as a name:

```
50bda6102c8dd57a5ead84e99d493776.js@ -> package1.js
50bda6102c8dd57a5ead84e99d493776.js.gz@ -> package1.js.gz
```

Then, when the Rails app is running in production, include_javascripts(:package1) could instead generate:

```
<script src="/assets/50bda6102c8dd57a5ead84e99d493776.js" type="text/javascript"></script>
```

Also, a deployment script could copy these MD5-named assets to CDNs after running `jammit`.

Is this a crazy idea? Is there a way to do something similar already?

**Comment by adamhooper** [comment]
Whoa, no comments in five years? Time to complain ;).

The thing with cache-busting is: it isn't what anybody wants. People actually want asset versioning. Here's the difference:

* Cache-busting (with `?TIMESTAMP`): tells the web browser to use an uncached version
* Asset versioning (with `...-fingerprint.*`): serves a different file

This is important _during_ deploy. Assume you're deploying and it takes a while. You upload new JavaScript, and then 2min later you finish uploading all the HTML that points to it. Here's what happens to a user who comes in 1min into the deploy process _with a clean browser cache_:

* Cache-busting: the old HTML references the new JavaScript, which breaks.
* Asset versioning: the old HTML references the old JavaScript, which works.

Furthermore, `?TIMESTAMP=*` does different things on different caching proxies.

Cache-busting isn't what anybody wants. People want asset versioning.
